/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF, useAnimations } from '@react-three/drei';
import { GroupProps } from '@react-three/fiber';
import React, { useEffect, useRef } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader';

const MODEL = '/3d-models/korrigan-tanning.gltf';

type GLTFResult = GLTF & {
  nodes: {
    Femme: THREE.SkinnedMesh;
    root: THREE.Bone;
  };
  materials: {
    ['color_main.004']: THREE.MeshStandardMaterial;
  };
};

// type ActionName = 'pose_femme';
// type GLTFActions = Record<ActionName, THREE.AnimationAction>;

const Korrigan: React.FC<GroupProps> = (props: GroupProps) => {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF(MODEL) as unknown as GLTFResult;
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions['pose_femme']?.play();
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={0.15} castShadow>
        <primitive object={nodes.root} />
        <skinnedMesh
          geometry={nodes.Femme.geometry}
          material={materials['color_main.004']}
          skeleton={nodes.Femme.skeleton}
          castShadow
        />
      </group>
    </group>
  );
};
export default Korrigan;
useGLTF.preload(MODEL);
