/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import { GroupProps } from '@react-three/fiber';
import React, { useRef } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader';

const MODEL = '/3d-models/car.gltf';

type GLTFResult = GLTF & {
  nodes: {
    body: THREE.Mesh;
    body_1: THREE.Mesh;
    body_2: THREE.Mesh;
    body_3: THREE.Mesh;
    body_4: THREE.Mesh;
    body_5: THREE.Mesh;
    steer: THREE.Mesh;
    tires: THREE.Mesh;
  };
  materials: {
    ['gray.002']: THREE.MeshStandardMaterial;
    ['light_f.002']: THREE.MeshStandardMaterial;
    ['body.002']: THREE.MeshStandardMaterial;
    glass_crack: THREE.MeshStandardMaterial;
    ['glassgray.002']: THREE.MeshStandardMaterial;
    Light: THREE.MeshStandardMaterial;
    ['rubber.002']: THREE.MeshStandardMaterial;
  };
};

const Car: React.FC<GroupProps> = (props: GroupProps) => {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF(MODEL) as unknown as GLTFResult;
  return (
    <group ref={group} {...props} castShadow>
      <mesh geometry={nodes.body.geometry} material={materials['gray.002']} castShadow />
      <mesh geometry={nodes.body_1.geometry} material={materials['light_f.002']} castShadow />
      <mesh geometry={nodes.body_2.geometry} material={materials['body.002']} castShadow />
      <mesh geometry={nodes.body_3.geometry} material={materials.glass_crack} castShadow />
      <mesh geometry={nodes.body_4.geometry} material={materials['glassgray.002']} castShadow />
      <mesh geometry={nodes.body_5.geometry} material={materials.Light} castShadow />
      <mesh geometry={nodes.steer.geometry} material={materials['gray.002']} castShadow />
      <mesh geometry={nodes.tires.geometry} material={materials['rubber.002']} castShadow />
    </group>
  );
};
export default Car;
useGLTF.preload(MODEL);
