/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import { GroupProps } from '@react-three/fiber';
import React, { createRef } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader';

type GLTFResult = GLTF & {
  nodes: {
    tires: THREE.Mesh;
    steer: THREE.Mesh;
    interior003: THREE.Mesh;
    interior003_1: THREE.Mesh;
    interior003_2: THREE.Mesh;
    interior003_3: THREE.Mesh;
    interior003_4: THREE.Mesh;
    interior003_5: THREE.Mesh;
  };
  materials: {
    ['rubber.002']: THREE.MeshStandardMaterial;
    ['gray.002']: THREE.MeshStandardMaterial;
    ['light_f.002']: THREE.MeshStandardMaterial;
    ['body.002']: THREE.MeshStandardMaterial;
    glass_crack: THREE.MeshStandardMaterial;
    ['glassgray.002']: THREE.MeshStandardMaterial;
    Light: THREE.MeshStandardMaterial;
  };
};

const Car: React.FC<GroupProps> = (props: GroupProps) => {
  const group = createRef<THREE.Group>();
  const { nodes, materials } = useGLTF(
    'https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/cybertruck/model.gltf',
  ) as unknown as GLTFResult;
  return (
    <group ref={group} {...props} castShadow>
      <mesh geometry={nodes.tires.geometry} material={materials['rubber.002']} castShadow />
      <mesh geometry={nodes.steer.geometry} material={nodes.steer.material} castShadow />
      <mesh
        geometry={nodes.interior003.geometry}
        material={nodes.interior003.material}
        castShadow
      />
      <mesh
        geometry={nodes.interior003_1.geometry}
        material={materials['light_f.002']}
        castShadow
      />
      <mesh geometry={nodes.interior003_2.geometry} material={materials['body.002']} castShadow />
      <mesh geometry={nodes.interior003_3.geometry} material={materials.glass_crack} castShadow />
      <mesh
        geometry={nodes.interior003_4.geometry}
        material={materials['glassgray.002']}
        castShadow
      />
      <mesh geometry={nodes.interior003_5.geometry} material={materials.Light} castShadow />
    </group>
  );
};
export default Car;
useGLTF.preload(
  'https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/cybertruck/model.gltf',
);
