/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import { GroupProps } from '@react-three/fiber';
import React, { useRef } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader';

const MODEL = '/3d-models/bookshelf.gltf';

type GLTFResult = GLTF & {
  nodes: {
    bookcaseWideFilled_broken: THREE.Mesh;
    bookcaseWideFilled_broken_1: THREE.Mesh;
    bookcaseWideFilled_broken_2: THREE.Mesh;
    bookcaseWideFilled_broken_3: THREE.Mesh;
    bookcaseWideFilled_broken_4: THREE.Mesh;
    bookcaseWideFilled_broken_5: THREE.Mesh;
    bookcaseWideFilled_broken_6: THREE.Mesh;
    bookcaseWideFilled_broken_7: THREE.Mesh;
  };
  materials: {
    ['BrownDark.050']: THREE.MeshStandardMaterial;
    ['PurpleDark.004']: THREE.MeshStandardMaterial;
    ['White.035']: THREE.MeshStandardMaterial;
    ['Metal.081']: THREE.MeshStandardMaterial;
    ['BlueDark.004']: THREE.MeshStandardMaterial;
    ['GreenDark.008']: THREE.MeshStandardMaterial;
    ['WoodDark.006']: THREE.MeshStandardMaterial;
    ['Black.031']: THREE.MeshStandardMaterial;
  };
};

const Bookshelf: React.FC<GroupProps> = (props: GroupProps) => {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials } = useGLTF(MODEL) as unknown as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, Math.PI / 2]} castShadow>
        <mesh
          geometry={nodes.bookcaseWideFilled_broken.geometry}
          material={materials['BrownDark.050']}
          castShadow
        />
        <mesh
          geometry={nodes.bookcaseWideFilled_broken_1.geometry}
          material={materials['PurpleDark.004']}
          castShadow
        />
        <mesh
          geometry={nodes.bookcaseWideFilled_broken_2.geometry}
          material={materials['White.035']}
          castShadow
        />
        <mesh
          geometry={nodes.bookcaseWideFilled_broken_3.geometry}
          material={materials['Metal.081']}
          castShadow
        />
        <mesh
          geometry={nodes.bookcaseWideFilled_broken_4.geometry}
          material={materials['BlueDark.004']}
          castShadow
        />
        <mesh
          geometry={nodes.bookcaseWideFilled_broken_5.geometry}
          material={materials['GreenDark.008']}
          castShadow
        />
        <mesh
          geometry={nodes.bookcaseWideFilled_broken_6.geometry}
          material={materials['WoodDark.006']}
          castShadow
        />
        <mesh
          geometry={nodes.bookcaseWideFilled_broken_7.geometry}
          material={materials['Black.031']}
          castShadow
        />
      </group>
    </group>
  );
};

export default Bookshelf;

useGLTF.preload(MODEL);
