/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 druid.gltf --types --keepnames
*/

import { useGLTF, useAnimations } from '@react-three/drei';
import { GroupProps, useGraph } from '@react-three/fiber';
import React, { useEffect, useMemo, useRef } from 'react';
import * as THREE from 'three';
import { GLTF, SkeletonUtils } from 'three-stdlib';

const MODEL = '/3d-models/druid.gltf';

type ActionName = 'Idle' | 'Cast' | 'Wave';

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    Main_Mesh: THREE.SkinnedMesh;
    ['DEF-PELVIS']: THREE.Bone;
  };
  materials: {
    Material: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

interface DruidProps extends GroupProps {
  animationKey?: ActionName;
}

const Druid: React.FC<DruidProps> = ({ animationKey = 'Idle', ...props }) => {
  const group = useRef<THREE.Group>(null);
  const { scene, animations } = useGLTF(MODEL);
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult;
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    const action = actions[animationKey];
    action?.reset().fadeIn(0.2).play();
    return () => {
      action?.fadeOut(0.2);
    };
  }, [actions, animationKey]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="Armature" rotation={[-Math.PI / 2, 0, 0]} scale={19.937}>
            <primitive object={nodes['DEF-PELVIS']} />
          </group>
          <skinnedMesh
            name="Main_Mesh"
            geometry={nodes.Main_Mesh.geometry}
            material={materials.Material}
            skeleton={nodes.Main_Mesh.skeleton}
            morphTargetDictionary={nodes.Main_Mesh.morphTargetDictionary}
            morphTargetInfluences={nodes.Main_Mesh.morphTargetInfluences}
          />
        </group>
      </group>
    </group>
  );
};

export default Druid;

useGLTF.preload(MODEL);
