/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF, useAnimations } from '@react-three/drei';
import { GroupProps } from '@react-three/fiber';
import React, { useEffect, useRef } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader';

const MODEL = '/3d-models/old-korrigan.gltf';

type ActionName = 'course_vieux' | 'pose_vieux';

type GLTFResult = GLTF & {
  nodes: {
    Vieux: THREE.SkinnedMesh;
    root: THREE.Bone;
  };
  materials: {
    ['color_main.001']: THREE.MeshStandardMaterial;
  };
};

interface OldKorriganProps extends GroupProps {
  animationKey?: ActionName;
}

const OldKorrigan: React.FC<OldKorriganProps> = ({ animationKey = 'pose_vieux', ...props }) => {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF(MODEL) as unknown as GLTFResult;
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    const action = actions[animationKey];
    action?.reset().fadeIn(0.2).play();
    return () => {
      action?.fadeOut(0.2);
    };
  }, [actions, animationKey]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={0.15}>
        <primitive object={nodes.root} />
        <skinnedMesh
          geometry={nodes.Vieux.geometry}
          material={materials['color_main.001']}
          skeleton={nodes.Vieux.skeleton}
        />
      </group>
    </group>
  );
};

export default OldKorrigan;

useGLTF.preload(MODEL);
