/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF, useAnimations } from '@react-three/drei';
import { GroupProps } from '@react-three/fiber';
import React, { createRef, useEffect } from 'react';
import * as THREE from 'three';
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader';

type GLTFResult = GLTF & {
  nodes: {
    Vieux: THREE.SkinnedMesh;
    root: THREE.Bone;
  };
  materials: {
    ['color_main.001']: THREE.MeshStandardMaterial;
  };
};

// type ActionName = 'course_vieux' | 'pose_vieux';
// type GLTFActions = Record<ActionName, THREE.AnimationAction>;

const OldKorrigan: React.FC<GroupProps> = (props: GroupProps) => {
  const group = createRef<THREE.Group>();
  const { nodes, materials, animations } = useGLTF(
    'https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/old-korrigan/model.gltf',
  ) as unknown as GLTFResult;
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions['pose_vieux']?.play();
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={0.15}>
        <primitive object={nodes.root} />
        <skinnedMesh
          geometry={nodes.Vieux.geometry}
          material={materials['color_main.001']}
          skeleton={nodes.Vieux.skeleton}
        />
      </group>
    </group>
  );
};

export default OldKorrigan;

useGLTF.preload(
  'https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/old-korrigan/model.gltf',
);
