on:
  workflow_call:
    inputs:
      spec:
        required: true
        type: string
    secrets:
      ENEIGHBOR_API:
        required: true
      DB_TYPE:
        required: true
      DB_HOST:
        required: true
      DB_PORT:
        required: true
      DB_USERNAME:
        required: true
      DB_PASSWORD:
        required: true
      DB_DATABASE:
        required: true
      DB_CONN:
        required: true
      DB_SSL:
        required: true

jobs:
  cypress-e2e-testing:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Download build output
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Show repo structure
        run: |
          ls -lad

      - name: Install Cypress
        run: npm i cypress@13.6.0

      - name: Generate .env.local
        run: echo '${{ toJSON(secrets) }}' | jq -r 'keys[] as $k | "\($k)=\(.[$k])"' >> .env.local

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          ENEIGHBOR_API: ${{ secrets.ENEIGHBOR_API }}
          DB_TYPE: ${{ secrets.DB_TYPE }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT}}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD}}
          DB_DATABASE: ${{ secrets.DB_DATABASE}}
          DB_CONN: ${{ secrets.DB_CONN}}
          DB_SSL: ${{ secrets.DB_SSL}}

        with:
          start: npm run preview:run
          wait-on: 'http://localhost:8000'
          install: false
          spec: ${{ inputs.spec }}

      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
